add task1 project and postman json file
LanSlider/iTechLab18 pull request #7
Opened 2018-08-14 10:27 UTC by LanSlider

2018-08-14 12:49 UTC, DenomikoN requested changes
Посмоти комментарии - там пару моментов, которые нужно исправить

2018-08-14 12:49 UTC, DenomikoN commented on netcore/Task1/APISum/Models/ResultModel.cs
> +        [RegularExpression("^[1-9][0-9]*$", ErrorMessage = "Value must be positive")]
Зачем валидация в ResultModel?

2018-08-14 12:49 UTC, DenomikoN commented on netcore/Task1/APISum/Models/ValueModel.cs
> +        [RegularExpression("^[1-9][0-9]*$", ErrorMessage = "Value must be positive")]
Регулярные выражения мощный, но не совсем подходящий вариант, лучше RangeAttribute

2018-08-14 12:49 UTC, DenomikoN commented on netcore/Task1/APISum/Controllers/ValuesController.cs
> +            return Ok(new ResultModel { A = (int)model.Value1, B = (int)model.Value2, Sum = (int)(model.Value1 + model.Value2) });
В данном случае, сложение - это бизнесс логика, в идеале её нужно выносить в отдельный класс и не мешать в контроллер, поскольку она может быть переиспользованна. Попробуй создать новый класс SumValuesService в который перенёсешь логику и инжекти его в конструктор сервиса.

2018-08-15 08:57 UTC, EvgenyRazumov commented on netcore/Task1/APISum/Controllers/ValuesController.cs
> +        [HttpGet]
старайся после каждой `}` оставлять пустую строку. Очень сильно улучшает читабельность кода.

2018-08-15 08:57 UTC, EvgenyRazumov commented on netcore/Task1/APISum/Services/SumValuesService.cs
> +        public ResultModel SumValues(ValueModel valueModel)
Бизнес логика должна работать со своими моделями, которые не зависят от уровня представления (в нашем случае API).
Банальный пример: значения A и B в ValueModel имеют тип `nullable`, а в метод SumValues они должны приходить not nullable.
В данном случае нужно или просто передавать 2 аргумента, или создавать отдельную модель для SumValuesService и на уровне представления заполнять ее.

2018-08-15 13:11 UTC, merged