Develop netcore2
LanSlider/iTechLab18 pull request #8
Opened 2018-08-14 10:31 UTC by LanSlider

2018-08-14 13:02 UTC, DenomikoN requested changes
Смотри замечания

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Controllers/ShipsController.cs
> +            return Ok(_shipDataService.GetData());
Желательно сохранять в локальной переменной - так проще читать.

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +            _dataSource = config["ShipsDataURL"];
Лучше принимать сразу URL

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +            var client = new RestClient(new Uri(_dataSource));
Клиент нужно создавать только единожды

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +            var response = client.Execute(request);
Есть generic Execute метод который сразу десериализует ответ в определенный тип.

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +            var starShipsList = JsonConvert.DeserializeObject<Starships>(response.Content);
С RestSharp тебе не нужно беспокоиться о сериализации

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +    public class ShipDataService : IShipDataService
Добавить обработку исключений

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +            Starships starshipsList = new Starships();
Не нужно инициализировать - всеравно затрется в сл вызове.

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Startup.cs
> +            services.AddTransient<IShipDataService, ShipDataService>();
Сервис может быть инжектирован как Singleton, для того чтобы не пересоздавать RestClient

2018-08-14 13:02 UTC, DenomikoN commented on netcore/Task2/APITransform/Models/Starship.cs
> +        public string name { get; set; }
Именование не соответствует принятым нормам в C# - попробуй исправить с помощью атрибутов (SerializeAsAttribute)

2018-08-15 08:53 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +        public List<Starship> AddIndexToList(List<Starship> list, int index = 0)
1. Насколько я вижу, этот метод не является частью интерфейса. Так что стоит его делать private, protected и т.д.
2. Проставление индекса относится уже к маппингу, а не к логике получения данных. Что, если `https://swapi.co/api/starships` уже возвращал бы в результате поле `Index` с каким то своим значением, которое тебе нужно было бы просто напросто игнорировать?

2018-08-15 08:53 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +            Starships starShipsList = new Starships();
Для таких простых объявлений я бы посоветовал использовать единый стиль: т.е. или var или явный тип. Смешивать не стоит

2018-08-15 08:53 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +                    throw new ApplicationException("Error: Invalid data source");
Тип исключения очень общий (по сути, базовый для всех исключений приложения).
Необходимо использовать более узконаправленный тип исключения. Если нету подходящего - создать свой.

2018-08-15 08:53 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +        public async Task<ShipData> GetAllDataAsync()
Начало этого метода точь в точь повторяет предыдущий.
Как насчет переиспользования кода?

2018-08-15 08:53 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +                _client.BaseUrl = new Uri(shipDataNext.Next);
Я думаю, что здесь можно было бы использовать тот же самый код, который уже описан выше для первой страницы.

2018-08-15 13:48 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Controllers/ShipsController.cs
> +            return Json(new SuccessJsonResult(data));
we can place it inside `try` block

2018-08-15 13:48 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipIndexService.cs
> +                throw new BussinessException("List is null");
в данном случае получается, что пользователю вернется на UI ошибка "List is null".
Насколько она вообще информативна? какой list подразумевается?

2018-08-15 13:48 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipIndexService.cs
> +            for (int i = index; i < list.Count(); i++)
попробуй использовать linq вместо этого цикла?
list.foreach

2018-08-15 13:48 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/ViewModels/BaseJsonResult.cs
> +        public Starships data { get; set; }
Предпочтительнее использовать Generic, чтобы в дальнейшем этот же BaseJsonResult можно было использовать и под другие возвращаемые результаты

2018-08-15 13:48 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/ViewModels/BaseJsonResult.cs
> +        public string errorMessage { get; set; }
в C# свойства принято объявлять с большой буквы.
Если при сериализации нужно получить название свойства с маленькой буквы - используй аттрибут.

2018-08-16 07:54 UTC, EvgenyRazumov commented on netcore/Task2/APITransform/Services/ShipDataService.cs
> +        private string GetPageRequest(Uri url)
GetPageRequest должен принимать string и из этой строки доставать номер страницы.
Нету смысла создавать объект Uri выше и размазывать эту логику за пределами метода.

2018-08-16 08:15 UTC, merged